### ISSUE TITLE
setDaysHighlight doesn't work in Safari

### ISSUE THREAD

**Issue by newgi** [maurovieirareis/hello-week#23] opened 2019-05-05 12:54 UTC
there are no console errors and getDaysHighlight gives back the same array of events, but '.is-highlight' classes are never added to the DOM.

The issue is present on the demo page as well, the days are not highlighted visually in Safari
https://mauroreisvieira.github.io/hello-week/#/docs/demos/highlight-dates

**Comment by mauroreisvieira** [comment] 2019-05-06 09:47
Hi @newgi thanks for your report. I will check a soon as possible.

**Comment by mauroreisvieira** [comment] 2019-05-09 11:12
Hi @newgi bug fixed in version [2.10.1](https://github.com/mauroreisvieira/hello-week/releases/tag/2.10.1).

TY!

**Comment by Markus-Berger** [comment] 2019-05-10 19:37
I believe this version may have broken the highlights on other browsers, as I can't see them anywhere now. (Tested on Chrome, Firefox, Edge, no console errors) 

The issue is also present on the demo paged linked in the original issue - although the date range from 2019-06-02 to 2019-06-14 is shown (2019-06-01 is not highlighted though, while judging from the description it should be.)

**Comment by fabio-craq** [comment] 2019-05-14 10:21
yes, same here.
This update broken the daysHighlight parameter and the setDaysHighlight function.

need fix ASAP!! 

Thank you.

**Comment by mauroreisvieira** [comment] 2019-05-14 23:27
Hi @Markus-Berger and @fabio-craq I test in Chorme, FIrefox and Safri and dont have any error.

https://mauroreisvieira.github.io/hello-week/#/docs/demos/highlight-dates

**Comment by fabio-craq** [comment] 2019-05-15 08:20
ok so, can i ask you an example of how the setDaysHighlight function works?
For instance, i have an array of non contiguous days to highlight.

Thank you so much!

**Comment by fabio-craq** [comment] 2019-05-15 08:44
the example that you linked (https://mauroreisvieira.github.io/hello-week/#/docs/demos/highlight-dates) does not work. It only highlights the current day, not the ones that you passes as argument to daysHighlight.

**Comment by mauroreisvieira** [comment] 2019-05-16 10:39
@fabio-craq what is your timezone and OS? Because for me work's fine. :/

<img width="1011" alt="Screenshot 2019-05-16 at 11 38 17" src="https://user-images.githubusercontent.com/3084774/57847776-37d2ac80-77cf-11e9-838e-2b55a98943b2.png">

**Comment by fabio-craq** [comment] 2019-05-16 10:47
that's quite strange. I can see the June highlight exactly as you see it, but i can't see march (2019-03-22) nor december(2019-12-18) highlights that you have in your example.
I'm in Italy and i work on a mac with ma os 10.14.4

**Comment by fabio-craq** [comment] 2019-05-16 11:00
also the june example is not correct, because it takes only the first parameters ( ["2019-06-01", "2019-06-14"]) and not the second (["2019-08-16", "2019-04-29"])

**Comment by fabio-craq** [comment] 2019-05-16 11:05
it's also very strange that if i call myCalendar.getDaysHighlight() it prints  the right highlited days, while these days haven't the is-highlight class (see screenshot)
<img width="385" alt="Schermata 2019-05-16 alle 13 04 22" src="https://user-images.githubusercontent.com/23176237/57849264-22fc1600-77db-11e9-82d3-2aa4ae34faf2.png">

**Comment by Markus-Berger** [comment] 2019-05-16 17:40
@mauroreisvieira In your picture the first day of the date range is missing too. Per definition, it should start at '2019-06-01'. This is the same problem I have, all the single days and the first date of the date range aren't highlighted.

My OS and TZ: Windows, CEST

**Comment by DevBodin** [comment] 2019-05-19 02:28
My thanks for the hard work that clearly went into this calendar. I'm starting to see the light of day, but I too was completely missing any sort of formatting for anything outside of the 'today highlight.' It took longer than I'm ready to admit, but I finally found something that works:

 ```
       daysHighlight: [
            {
                days: [
                    ['2019-05-25', '2019-05-28']
                ],
            }
        ],
```

An array of objects with days as an array of arrays. It's quite the nest.
This accomplishes what I need for now, but if I figure out anything else, I'll be sure to let you know. (No luck with 'IS_SELECTED.')
(Afraid I'm not up on Typescript at the moment, or I'd dig into myself.)

**Comment by fabio-craq** [comment] 2019-05-19 08:29
Thank you @DevBodin, but in this way it highlights only the first date span, not the single days. For example if my array is ["2019-05-17"]["2019-05-16"]["2019-05-18"]["2019-05-22"]["2019-05-18"]["2019-05-25"] it highlights days from 17/05 to 19/05 (yes, is one day ahead), but 22/05 and 25/05 are just ignored.

**Comment by fabio-craq** [comment] 2019-05-19 08:55
at this point i don't know what to do because i need to publish the client's website in a week or so and this is the only thing that doesn't work. I'm afraid that if this won't work in a couple of days i have to switch to another calendar script. 
Some other debug information: 
- the old version (the one that didn't works with safari) works like a charm on other browsers;
- on my code its seems that days are actually set as highlighted, but there is no 'is-highlight' class in the day's html

I'll attach the screenshot the log of setDaysHighlight and getDaysHighlight in the javascript console to show you that it seems that the parameters are passed correctly 
This is the code that i use to populate the setDaysHighlight parameter.
Hope that there'll be a fix asap.

```php 
$.ajax({
	    url : ajax_object.ajaxurl,
	    type : 'post',
		dataType:'json',
	    data: {
			action: 'qchild_get_events_calendar',
			month : d.getTime() 
		},
	    success: function(data) {
			if (data) {
				var days = new Array();
				for(var prop in data) {
					var p = new Array(data[prop]);
					days.push({days: [data[prop]]});
				}
				myCalendar.setDaysHighlight(days);
				myCalendar.update();
			}
		}
	});
```

Thank you.

<img width="394" alt="Schermata 2019-05-19 alle 10 44 14" src="https://user-images.githubusercontent.com/23176237/57979933-46fe6800-7a24-11e9-8677-93c418467d59.png">

**Comment by mauroreisvieira** [comment] 2019-05-19 11:12
Hello everyone, I apologize for my late reply. But this week was impossible.

Today I made a small correction, in relation to the 1st day not to be highlighted, I do not know if it solved other problems. But I do not know why my days turn out well :(

Waiting feedback...

**Comment by fabio-craq** [comment] 2019-05-19 11:30
Hi @mauroreisvieira 
this new version seems to fix the setDaysHighlight problem!

you made it! thanks a lot!

**Comment by mauroreisvieira** [comment] 2019-05-19 11:31
TY @fabio-craq for your fast feedback. 

Sorry again for the huge delay.

**Comment by fabio-craq** [comment] 2019-05-20 07:46
no problem :-)

**Comment by mauroreisvieira** [comment] 2019-05-23 18:08
@newgi @fabio-craq can close the issue?

**Comment by fabio-craq** [comment] 2019-05-24 07:04
ok for me

**Comment by newgi** [comment] 2019-05-24 07:39
Sure, thank you!

**Closed as completed** 2019-05-27 08:47 UTC
Labels: bug
